# Fine-Tuning: BGE-M3 on TripLegal-CL

**Objective.** The central claim of the paper is that TripLegal-CL provides
an effective contrastive training signal for adapting dense bi-encoder
retrievers to the Spanish legal domain. To validate this, we fine-tune
`BAAI/bge-m3` — a strong multilingual encoder optimized for dense
retrieval and reranking — using contrastive learning on TripLegal-CL.
If the fine-tuned model consistently outperforms its baseline across
all IR metrics, this confirms that the corpus provides useful
domain-specific supervision.

**Dev evaluator.** During training, a dev evaluator (50K queries, 80K
corpus) runs every 100 steps to monitor convergence. It is drawn from
the **training region** (first 380K instances) and is intentionally
smaller for speed.

## 1. Environment Setup

In [1]:
!pip install -U "sentence-transformers>=3.0.1" "transformers>=4.48.0" datasets accelerate

Requirement already satisfied: sentence-transformers>=3.0.1 in /usr/local/lib/python3.12/dist-packages (5.2.2)
Requirement already satisfied: transformers>=4.48.0 in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers>=4.48.0
  Downloading transformers-5.1.0-py3-none-any.whl.metadata (31 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-4.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.1) (1.4.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.1) (2.9.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.1) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.1) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.1) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.1) (4.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=3.0.1) (4.67.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.3)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.0.1) (1.2.0)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.0.1) (1.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (1.13.1.3)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.1) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers>=3.0.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers>=3.0.1) (3.6.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers>=4.48.0) (8.3.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=3.0.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=3.0.1) (3.0.3)
Downloading transformers-5.1.0-py3-none-any.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 131.3 MB/s eta 0:00:00
Downloading datasets-4.5.0-py3-none-any.whl (515 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 38.4 MB/s eta 0:00:00
Downloading pyarrow-23.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (47.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 57.9 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets, transformers
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed datasets-4.5.0 pyarrow-23.0.0 transformers-5.1.0

## 2. Imports

In [2]:
import logging
import traceback

from datasets import load_dataset
from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerModelCardData,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
)
from sentence_transformers.evaluation import InformationRetrievalEvaluator
from sentence_transformers.losses import CachedMultipleNegativesRankingLoss
from sentence_transformers.training_args import BatchSamplers

logging.basicConfig(
    format="%(asctime)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.INFO,
)

## 3. Load Model

In [3]:
model = SentenceTransformer(
    "BAAI/bge-m3",
    model_card_data=SentenceTransformerModelCardData(
        language="es",
        license="apache-2.0",
        model_name="BGE-M3 trained on TripLegal-CL Legal Spanish.",
    ),
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

**Note:** Unlike multilingual-e5-large, BGE-M3 does **not** require
"query: " / "passage: " prefixes. Raw text is passed directly to
the encoder — no `prompts={}` parameter is needed in the training
arguments.

## 4. Prepare Data Helper

In [4]:
def select_first_pos(example):
    if example["pos"]:
        return {"query": example["query"], "pos": example["pos"][0]}

## 5. Load and Split Dataset

In [5]:
SEED = 42
TRAIN_N = 300_000
EVAL_N  = 50_000
TEST_N  = 30_000

base = load_dataset("wilfredomartel/TripLegal-CL", split="train").shuffle(seed=SEED)

# Disjoint ranges — no data leakage
train_dataset = base.select(range(0, TRAIN_N))
eval_dataset  = base.select(range(TRAIN_N, TRAIN_N + EVAL_N))
test_dataset  = base.select(range(TRAIN_N + EVAL_N, TRAIN_N + EVAL_N + TEST_N))

cols_to_remove = ["neg", "pos_score", "neg_score"]

train_dataset = train_dataset.remove_columns(cols_to_remove).map(select_first_pos)
eval_dataset  = eval_dataset.remove_columns(cols_to_remove).map(select_first_pos)
test_dataset  = test_dataset.remove_columns(cols_to_remove).map(select_first_pos)

print(f"Train: {len(train_dataset):,}")
print(f"Eval:  {len(eval_dataset):,}")
print(f"Test:  {len(test_dataset):,}")
print(train_dataset[0])

README.md:   0%|          | 0.00/428 [00:00<?, ?B/s]

data/train-00000-of-00005.parquet:   0%|          | 0.00/206M [00:00<?, ?B/s]

data/train-00001-of-00005.parquet:   0%|          | 0.00/206M [00:00<?, ?B/s]

data/train-00002-of-00005.parquet:   0%|          | 0.00/206M [00:00<?, ?B/s]

data/train-00003-of-00005.parquet:   0%|          | 0.00/206M [00:00<?, ?B/s]

data/train-00004-of-00005.parquet:   0%|          | 0.00/206M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/592382 [00:00<?, ? examples/s]

Map:   0%|          | 0/300000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Map:   0%|          | 0/30000 [00:00<?, ? examples/s]

Train: 300,000
Eval:  50,000
Test:  30,000
{'query': '¿Por qué la Primera Sala de la Suprema Corte de Justicia de la Nación declaró infundado el recurso de reclamación 456/2019, confirmando el desechamiento del recurso de revisión?', 'pos': 'La Primera Sala de la Suprema Corte de Justicia de la Nación declaró infundado el recurso de reclamación 456/2019, confirmando el desechamiento del recurso de revisión, al determinar que los agravios presentados por Manuel Contreras Ramos no combatían las razones del acuerdo de presidencia recurrido. El acuerdo de desechamiento se basó en la inexistencia de una cuestión propiamente constitucional, mientras que los agravios del recurrente se enfocaron en demostrar la importancia y trascendencia del asunto, sin desvirtuar la falta de un tema de constitucionalidad. La Sala aplicó la tesis 1a. XXXVI/2018 (10a.) para señalar que los agravios que no desvirtúan la inexistencia de una cuestión constitucional son inoperantes, y que la falta de un tema de constitucionalidad es suficiente para confirmar el desechamiento.'}

## 6. Loss Function and Training Arguments

In [6]:
loss = CachedMultipleNegativesRankingLoss(model, mini_batch_size=16)

run_name = "bge-m3-tripLegalCL-300k"

args = SentenceTransformerTrainingArguments(
    output_dir=f"models/{run_name}",
    num_train_epochs=1,
    per_device_train_batch_size=128,
    per_device_eval_batch_size=128,
    learning_rate=2e-5,
    warmup_ratio=0.03,
    fp16=True,
    bf16=False,
    batch_sampler=BatchSamplers.NO_DUPLICATES,
    # BGE-M3 does NOT use prompts — no prefixes needed
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=2,
    logging_steps=20,
    run_name=run_name,
)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

### How contrastive learning works in this training setup

> **Sources:** This explanation is based on the official `sentence-transformers`
> documentation and source code:
> - [MultipleNegativesRankingLoss — Losses documentation](https://sbert.net/docs/package_reference/sentence_transformer/losses.html)
> - [CachedMultipleNegativesRankingLoss — source code](https://github.com/huggingface/sentence-transformers/blob/main/sentence_transformers/losses/CachedMultipleNegativesRankingLoss.py)
> - [NoDuplicatesBatchSampler — Samplers documentation](https://sbert.net/docs/package_reference/sentence_transformer/sampler.html)
> - [Loss Overview — sentence-transformers](https://sbert.net/docs/sentence_transformer/loss_overview.html)
> - Original paper: *Efficient Natural Language Response Suggestion for Smart Reply*, Section 4.4 ([Henderson et al., 2017](https://huggingface.co/papers/1705.00652))

This section explains how the contrastive training signal is formed
during fine-tuning — the mechanism referred to as "contrastive learning"
in the paper.

**Training data format.** Each training example is a `(query, pos)` pair.
We do NOT explicitly provide negative passages to the trainer. Instead,
negatives are constructed automatically at training time through a
mechanism called **in-batch negatives**.

**In-batch negatives (InfoNCE / MNRL).** Given a batch of `B` pairs
`{(q₁, p₁), (q₂, p₂), ..., (qB, pB)}`, the loss function:

1. Encodes all `B` queries and all `B` passages into dense vectors.
2. Computes a `B × B` cosine similarity matrix between all queries
   and all passages.
3. For each query `qᵢ`, the passage `pᵢ` is the **positive** (correct
   answer), and all other passages `{p₁, ..., pᵢ₋₁, pᵢ₊₁, ..., pB}`
   are treated as **negatives** (wrong answers).
4. Applies cross-entropy loss to push `qᵢ` closer to `pᵢ` and away
   from all other passages in the batch.

```
Similarity matrix (batch_size=4 example):

              p₁     p₂     p₃     p₄
        q₁ [ 0.92   0.45   0.51   0.38 ]  ← maximize (q₁, p₁)
        q₂ [ 0.41   0.89   0.47   0.52 ]  ← maximize (q₂, p₂)
        q₃ [ 0.50   0.43   0.91   0.40 ]  ← maximize (q₃, p₃)
        q₄ [ 0.39   0.48   0.42   0.87 ]  ← maximize (q₄, p₄)

Diagonal = positive pairs (should be highest in each row)
Off-diagonal = in-batch negatives (should be lower)
```

This means that with a batch size of 128, each query has **127 implicit
negatives** per training step — all from the same legal domain, making
them naturally hard negatives.

**Why larger batches improve performance.** More samples per batch =
more in-batch negatives = harder contrastive signal = better
discrimination. This is why `CachedMultipleNegativesRankingLoss` is
valuable: it allows an effective batch size of 128 while only using
the GPU memory of `mini_batch_size=16`, by caching intermediate
embeddings (GradCache; Gao et al., 2021).

**Role of `BatchSamplers.NO_DUPLICATES`.** This sampler ensures that
no two samples in the same batch share identical text (query or
passage). This is critical because:

- If `p₃ == p₇` (duplicate passages in the batch), then `q₃` would
  have its own correct answer appearing as a "negative" — sending a
  contradictory gradient signal to the model.
- `NO_DUPLICATES` prevents this by checking for text duplicates when
  forming each batch.

**Important:** `NO_DUPLICATES` is a **sampler** (controls batch
composition), not a loss function. It does not generate negatives —
the loss function does that via the similarity matrix above.

**Summary of roles:**

| Component | Role |
|-----------|------|
| `CachedMNRL` (loss) | Constructs in-batch negatives from the B×B similarity matrix and computes cross-entropy |
| `NO_DUPLICATES` (sampler) | Ensures no duplicate texts in a batch, preventing false negatives |
| `per_device_train_batch_size=128` | Controls how many in-batch negatives each query sees (127) |
| `mini_batch_size=16` | Controls GPU memory usage (forward pass in chunks of 16) |

## 7. Build Dev Evaluator (monitoring during training)

This evaluator runs every 100 training steps to monitor convergence.
It uses data from the **training region** (first 380K instances), NOT
from the final evaluation region. It is intentionally smaller (50K
queries, 80K corpus) for speed.

In [7]:
queries = dict(enumerate(eval_dataset["query"]))

corpus_list = eval_dataset["pos"][:] + train_dataset.select(range(30_000))["pos"][:]
corpus = dict(enumerate(corpus_list))

relevant_docs = {idx: [idx] for idx in queries}

dev_evaluator = InformationRetrievalEvaluator(
    queries=queries,
    corpus=corpus,
    relevant_docs=relevant_docs,
    name="legal-spanish-bge-eval-50kq-80kd",
    show_progress_bar=True,
)

# Evaluate base model before training
dev_evaluator(model)

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [08:19<08:19, 499.94s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [13:21<00:00, 400.63s/it]

{'legal-spanish-bge-eval-50kq-80kd_cosine_accuracy@1': 0.7689,
 'legal-spanish-bge-eval-50kq-80kd_cosine_accuracy@3': 0.84754,
 'legal-spanish-bge-eval-50kq-80kd_cosine_accuracy@5': 0.87202,
 'legal-spanish-bge-eval-50kq-80kd_cosine_accuracy@10': 0.89908,
 'legal-spanish-bge-eval-50kq-80kd_cosine_precision@1': 0.7689,
 'legal-spanish-bge-eval-50kq-80kd_cosine_precision@3': 0.2825133333333332,
 'legal-spanish-bge-eval-50kq-80kd_cosine_precision@5': 0.174404,
 'legal-spanish-bge-eval-50kq-80kd_cosine_precision@10': 0.08990800000000002,
 'legal-spanish-bge-eval-50kq-80kd_cosine_recall@1': 0.7689,
 'legal-spanish-bge-eval-50kq-80kd_cosine_recall@3': 0.84754,
 'legal-spanish-bge-eval-50kq-80kd_cosine_recall@5': 0.87202,
 'legal-spanish-bge-eval-50kq-80kd_cosine_recall@10': 0.89908,
 'legal-spanish-bge-eval-50kq-80kd_cosine_ndcg@10': 0.8344443566149717,
 'legal-spanish-bge-eval-50kq-80kd_cosine_mrr@10': 0.8137107460317397,
 'legal-spanish-bge-eval-50kq-80kd_cosine_map@100': 0.8162723104482784}

## 8. Train

In [8]:
trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    loss=loss,
    evaluator=dev_evaluator,
)

trainer.train()

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.01s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.96s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.62s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.97s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.98s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.93s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.81s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.83s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.89s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.94s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.72s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.02s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.00s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.94s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.78s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.83s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.46s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.91s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.78s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.84s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.05s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.31s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.95s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.09s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.02s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.01s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.08s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.06s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.79s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.13s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:17<01:17, 77.73s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.31s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.26s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.26s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.12s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.12s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.03s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:05<00:00, 62.97s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.41s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:07<00:00, 63.52s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.08s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.03s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.66s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.44s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.88s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:07<00:00, 63.57s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=2344, training_loss=0.01610696719444449, metrics={'train_runtime': 15722.0017, 'train_samples_per_second': 19.082, 'train_steps_per_second': 0.149, 'total_flos': 0.0, 'train_loss': 0.01610696719444449, 'epoch': 1.0})

## 9. Post-Training Evaluation and Save

Running the evaluators after training serves two purposes: (1) confirm
final metrics, and (2) **log results into the model card** — Hugging Face
automatically includes the last evaluation scores in the model card
when pushing to the Hub.

We evaluate on both the **dev set** (50K queries) and a held-out **test
set** (30K queries, 20K corpus) to provide two independent performance
snapshots in the model card.

In [9]:
# Re-run dev evaluator — results are logged into the model card
dev_evaluator(model)

# Test set evaluation (30K queries, 20K corpus) — also logged into model card
queries = dict(enumerate(test_dataset["query"]))
corpus_list = test_dataset["pos"][:] + train_dataset.select(range(20_000))["pos"][:]
corpus = dict(enumerate(corpus_list))

relevant_docs = {idx: [idx] for idx in queries}
test_evaluator = InformationRetrievalEvaluator(
    queries=queries,
    corpus=corpus,
    relevant_docs=relevant_docs,
    name="legal-spanish-bge-test-30kq-50kd",
    show_progress_bar=True,
)
test_evaluator(model)

# Save the trained model
final_output_dir = f"models/{run_name}/final"
model.save_pretrained(final_output_dir)

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/2 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks:  50%|█████     | 1/2 [01:18<01:18, 78.06s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 2/2 [02:06<00:00, 63.02s/it]

Batches:   0%|          | 0/938 [00:00<?, ?it/s]

Corpus Chunks:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Corpus Chunks: 100%|██████████| 1/1 [01:16<00:00, 76.93s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## 10. Push to Hub

In [10]:
try:
    model.push_to_hub(run_name)
except Exception:
    logging.error(
        f"Error uploading model to Hub:\n{traceback.format_exc()}"
        f"Model is saved locally at: {final_output_dir}\n"
        f"To retry: model = SentenceTransformer('{final_output_dir}')\n"
        f"Then: model.push_to_hub('{run_name}')"
    )

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpbtk98yeq/tokenizer.json:  50%|####9     | 8.34MB / 16.8MB

  ...tk98yeq/model.safetensors:   1%|1         | 24.7MB / 2.27GB